version: '3.4'

services:
  labs:
    image: labs
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:2022 discr.py "]
    ports:
      - 2022:2022
